baseURL = "https://yhakng.net/"
languageCode = "en-us"
title = "YHKANG"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Life, the universe, and everything"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Life, the universe, and everything"
  keywords = "homepage, blog, programming"
  images = [""]

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:hi@yhkang.net"

  [[params.social]]
    name = "github"
    url  = "https://github.com/yhkang/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/_yhkang/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "yhkang"
    subtitle = "Life, the universe, and everything"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText     = "$ cd /home/yhkang/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "https://blog.yhkang.net/"

  [[menu.main]]
    identifier = "newsletter"
    name       = "Newsletter"
    url        = "https://yhkang.zhubai.love/"
